# Generated by Django 3.2.19 on 2023-06-22 14:36

from django.db import migrations

ROLE_NAME_INSPECTOR = "Inspector"
ROLE_NAME_EMPLOYER = "Employer"


def _get_role(role_name, role_model):
    return role_model.objects.filter(name=role_name).first()


def _create_role(role_name, role_model):
    role = _get_role(role_name, role_model)
    if not role:
        role = role_model(name=role_name, is_blocked=False, is_system=0)
        role.save()


def _delete_role(role_name, role_model):
    role = _get_role(role_name, role_model)
    if role:
        role.delete()


def on_migration(apps, schema_editor):
    role_model = apps.get_model("core", "role")
    _create_role(ROLE_NAME_INSPECTOR, role_model)
    _create_role(ROLE_NAME_EMPLOYER, role_model)


def on_migration_reverse(apps, schema_editor):
    role_model = apps.get_model("core", "role")
    _delete_role(ROLE_NAME_INSPECTOR, role_model)
    _delete_role(ROLE_NAME_EMPLOYER, role_model)


class Migration(migrations.Migration):
    dependencies = [
        ('msystems', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(on_migration, on_migration_reverse)
    ]
