# Generated by Django 3.2.19 on 2023-06-22 14:36

from django.db import migrations

from core.models import Role

ROLE_NAME_INSPECTOR = "Inspector"
ROLE_NAME_EMPLOYER = "Employer"


def _get_role(role_name):
    return Role.objects.filter(name=role_name).first()


def _create_role(role_name):
    role = _get_role(role_name)
    if not role:
        role = Role(name=role_name, is_blocked=False, is_system=0)
        role.save()


def _delete_role(role_name):
    role = _get_role(role_name)
    if role:
        role.delete()


def on_migration(apps, schema_editor):
    _create_role(ROLE_NAME_INSPECTOR)
    _create_role(ROLE_NAME_EMPLOYER)


def on_migration_reverse(apps, schema_editor):
    _delete_role(ROLE_NAME_INSPECTOR)
    _delete_role(ROLE_NAME_EMPLOYER)


class Migration(migrations.Migration):
    dependencies = [
        ('msystems', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(on_migration, on_migration_reverse)
    ]
