# Generated by Django 3.2.21 on 2023-11-03 16:46

from django.db import migrations

from core.models import Role, RoleRight

POLICY_HOLDER_SEARCH_PERM = [150101, 150201, 150301]
ROLE_NAME_INSPECTOR = "Inspector"
ROLE_NAME_EMPLOYER = "Employer"


def add_rights(role_name):
    role = Role.objects.get(name=role_name)
    for right_id in POLICY_HOLDER_SEARCH_PERM:
        if not RoleRight.objects.filter(validity_to__isnull=True, role=role, right_id=right_id).exists():
            _add_right_for_role(role, right_id)


def _add_right_for_role(role, right_id):
    RoleRight.objects.create(role=role, right_id=right_id, audit_user_id=1)


def remove_rights(role_id):
    RoleRight.objects.filter(
        role__is_system=role_id,
        right_id__in=POLICY_HOLDER_SEARCH_PERM,
        validity_to__isnull=True
    ).delete()


def on_migration(apps, schema_editor):
    add_rights(ROLE_NAME_INSPECTOR)
    add_rights(ROLE_NAME_EMPLOYER)


def on_reverse_migration(apps, schema_editor):
    remove_rights(ROLE_NAME_INSPECTOR)
    remove_rights(ROLE_NAME_EMPLOYER)


class Migration(migrations.Migration):

    dependencies = [
        ('msystems', '0002_add_roles'),
    ]

    operations = [
    ]
